apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telegram-forwarder.fullname" . }}
  labels:
    {{- include "telegram-forwarder.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "telegram-forwarder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "telegram-forwarder.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.werf.image.telegramForwarder }}"
          volumeMounts:
            - name: secret
              mountPath: /app/.env
              subPath: .env
            - name: secret
              mountPath: /app/chat_list.json
              subPath: chat_list.json
      volumes:
        - name: secret
          secret:
            secretName: {{ include "telegram-forwarder.fullname" . }}

